version: '2.4'
services:
  jupyter:
    environment:
      - JUPYTER_PASSWORD=simple
    image: jupyter/minimal-notebook:ad3574d3c5c7
    ports:
      - "8888:8888"
    user: 1000:1000
    working_dir: /src
    command: jupyter notebook
    volumes:
      - .:/src
      ## note: notebook_dir=/src/notebooks, root_dir=/home/jovyan
      - ./notebooks:/home/jovyan/notebooks
      ## note: notebook_dir=/src, root_dir=/home/jovyan
      # - ./notebooks:/home/jovyan/notebook
      - ./jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py:ro
